services:
  phoson:
    build: .
    container_name: phoson
    volumes:
      - ./data:/phoson/data
      - ./llm:/phoson/llm
      - ./notebooks:/phoson/notebooks
      - ./scripts:/phoson/scripts
      - ./main.py:/phoson/main.py
      - ./pyproject.toml:/phoson/pyproject.toml
      - ./uv.lock:/phoson/uv.lock
      - ./.python-version:/phoson/.python-version
    ports:
      - "8000:8000"
    command: sleep infinity